name: AppVault
options:
  bundleIdPrefix: com.appvault
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15"
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: ""
    TARGETED_DEVICE_FAMILY: "1"
    SUPPORTS_MAC_DESIGNED_FOR_IPAD: "NO"

targets:
  AppVault:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: AppVault
        excludes:
          - "**/*.entitlements"
    info:
      path: AppVault/Info.plist
      properties:
        CFBundleDisplayName: AppVault
        CFBundleName: AppVault
        CFBundleIdentifier: com.appvault.app
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        CFBundleIconName: AppIcon
        LSRequiresIPhoneOS: true
        UIDeviceFamily:
          - 1
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        "UISupportedInterfaceOrientations~ipad":
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UILaunchScreen:
          UIColorName: "AccentColor"
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        NSFaceIDUsageDescription: "AppVault usa Face ID para desbloquear apps de forma segura."
        CFBundleURLTypes:
          - CFBundleURLSchemes:
              - appvault
        LSApplicationQueriesSchemes:
          - instagram
          - tiktok
          - twitter
          - fb
          - snapchat
          - bereal
          - pinterest
          - threads
          - whatsapp
          - tg
          - discord
          - fb-messenger
          - signal
          - youtube
          - nflx
          - spotify
          - twitch
          - disneyplus
          - roblox
          - minecraft
          - linkedin
          - ms-outlook
          - googlegmail
          - uber
          - comgooglemaps
          - mercadolibre
          - ifood
          - shopee
          - amazon-mobile-shopping
          - reddit
          - prime-video
          - deezer
          - kwai
          - shakeit
    entitlements:
      path: AppVault/AppVault.entitlements
      properties:
        com.apple.developer.family-controls: true
        com.apple.security.application-groups:
          - group.com.appvault.shared
        keychain-access-groups:
          - $(AppIdentifierPrefix)com.appvault.app
    dependencies:
      - sdk: FamilyControls.framework
      - sdk: ManagedSettings.framework
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.appvault.app
        INFOPLIST_FILE: AppVault/Info.plist
        CODE_SIGN_STYLE: Manual
        ENABLE_BITCODE: "NO"
